node {

  // config 
  def to = emailextrecipients([
          [$class: 'CulpritsRecipient'],
          [$class: 'DevelopersRecipient'],
          [$class: 'RequesterRecipient']
  ])

  // job
  try {
    stage('build') {
      sh 'cd /home/omar/Desktop'
      def images = [sh './reg-linux-amd64 -k -r myregistry.com:5000 ls']
    }
    stage('test') {
      for (image in images)
       {
        File file = new File("/home/omar/Desktop/rapport.html").withWriter('utf-8')
         { 
               writer -> writer.writeLine sh' /reg-linux-amd64 vulns --clair image chrome'
         } 
         def derniere_ligne= "${file.length()}"
        if ()
         {
           sh 'exit 1'
         }
       }
    }
  } catch(e) {
    // mark build as failed
    currentBuild.result = "FAILURE";
    // set variables
    def subject = "${env.JOB_NAME} - Build #${env.BUILD_NUMBER} ${currentBuild.result}"
    def content = '${file,template="html"}'

    // send email
    if(to != null && !to.isEmpty()) {
      emailext(body: content, mimeType: 'text/html',
         replyTo: '$DEFAULT_REPLYTO', subject: subject,
         to: to, attachLog: true )
    }

    // mark current build as a failure and throw the error
    throw e;
  }
}
